
### 회원가입 1
POST http://localhost:9999/user/join
Content-Type: application/json

{
  "userAccount": "test1234",
  "password": "qwer1234",
  "phone": "12341234",
  "nickName": "aaaaaa"
}

### 회원가입 2
POST http://localhost:9999/user/join
Content-Type: application/json

{
  "userAccount": "qwe",
  "password": "qwe",
  "phone": "112233"
}


### 로그인 1
POST http://localhost:9999/auth/login
Content-Type: application/json

{
  "userAccount": "test1234",
  "password": "qwer1234"
}

### 로그인 2
POST http://localhost:9999/auth/login
Content-Type: application/json

{
  "userAccount": "qwe",
  "password": "qwe"
}

### 현재 로그인 사용자 정보 불러오기
GET http://localhost:9999/user/currentUserAccount


### 현재 로그인 사용자 구독여부 0 or 1
GET http://localhost:9999/user/currentUserPlan


### 현재 로그인 사용자 구독변경 무료 > 유료
PUT http://localhost:9999/payment/changeUserPlanFreeToPaid


### 로그아웃
GET http://localhost:9999/auth/logout


### 인증상태 체크
GET http://localhost:9999/auth/status


### 아이디 중복 체크
GET http://localhost:9999/user/chkIdDuplicate?id=test12345


### 현재 유저 부가정보
GET http://localhost:9999/user/currentUserProfile


### 유저정보 수정
PUT http://localhost:9999/user/updateUser
Content-Type: application/json

{
  "userAccount": "test1234",
  "phone": "123123123",
  "nickName": "TESTNAME"
}


### 아이디 찾기 - 전화번호 기반 유저 찾기
POST http://localhost:9999/user/findUserByPhone?inputPhone=12341234


