
### 회원가입
POST http://localhost:9999/user/join
Content-Type: application/json

{
  "userAccount": "test1234",
  "password": "qwer1234"
}


### 로그인
POST http://localhost:9999/auth/login
Content-Type: application/json

{
  "userAccount": "test1234",
  "password": "qwer1234"
}

### 현재 로그인 사용자 정보 불러오기
GET http://localhost:9999/user/currentUserAccount


### 현재 로그인 사용자 구독여부 0 or 1
GET http://localhost:9999/user/currentUserPlan


### 현재 로그인 사용자 구독변경 무료 > 유료
PUT http://localhost:9999/payment/changeUserPlanFreeToPaid


### 로그아웃
GET http://localhost:9999/auth/logout


### 인증상태 체크
GET http://localhost:9999/auth/status



