
### 주식명 검색
GET http://localhost:9999/pred/stockNameSearch?keyword=삼성


### 주식명 검색
GET http://localhost:9999/pred/showSelectedEntireData
Content-Type: application/json

{
  "startDate": "20210101",
  "endDate": "20210110",
  "ticker":"005930"
}
